### ISSUE TITLE
[TF 1.14] Conv model broken

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#93]
On 1.14, `./sticker-write-conv-graph shapes graph` fails with:

~~~py
Traceback (most recent call last):
  File "./sticker-write-conv-graph", line 41, in <module>
    create_graph(ConvModel, args)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/write_helper.py", line 30, in create_graph
    model(args=args, shapes=shapes)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/conv_model.py", line 178, in __init__
    mask=self.mask)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/conv_model.py", line 56, in dilated_convolution
    sharing=sharing)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/conv_model.py", line 90, in residual_block
    keep_prob=keep_prob)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/conv_model.py", line 134, in residual_unit
    padding="same"))(x)
  File "/Users/tobiasputz/sticker/sticker-graph/sticker_graph/weight_norm.py", line 51, in __init__
    self._track_checkpointable(layer, name='layer')
AttributeError: 'WeightNorm' object has no attribute '_track_checkpointable'
~~~

@danieldk 

Seems like more breaking changes were introduced in 1.14.

**Comment by twuebi** [comment]
Seems like a simple rename to `_track_trackable`

https://github.com/tensorflow/tensorflow/commit/bd36b48c555b2d46c41a179ed9f27a04806e9e66

> No API changes in this CL. Just more refactoring for a future API change.

I guess we'll see.
